Test Pattern option
computerlyrik/dymoprint pull request #89
Opened 2023-11-08 19:13 UTC by tomek-szczesny

Here's a little pattern generating code. It may have to be worked on because I'm not sure if it's sent to the printer faithfully. 

The bigger pattern indeed sends more data to the printer even though its physical size is the same, so I reckon this should work.

2023-11-08 21:01 UTC, maresb requested changes

2023-11-08 21:01 UTC, maresb commented on src/dymoprint/labeler.py
> +        #    raise ValueError
You can just delete this.

Interesting how `tape_size_mm` isn't actually doing anything. It's only used in `chainMark`, whatever that means. Let's leave that part in, just so `chainMark` isn't explicitly broken.

```suggestion
        self.tape_size_mm
```

2023-11-08 21:01 UTC, maresb commented on src/dymoprint/command_line.py
> +        args.text = " "
Ya, this is annoying, but not worth properly fixing in this PR. Does `""` work?

2023-11-08 21:08 UTC, maresb commented on src/dymoprint/command_line.py
> +        args.text = " "
Ah, nevermind, I see that you're trying to do this as a solution to #88. (I was thinking this was about something else.)

CLI parameter validation happens in the Click library which is pretty idiosyncratic, so don't worry about it.

2023-11-08 21:09 UTC, maresb commented on src/dymoprint/command_line.py
> +        args.text = " "
```suggestion
```

2023-11-08 21:20 UTC, tomek-szczesny commented
Before this gets pulled, I'd like to add some horizontal lines after the checkerboard. I've got a nice idea for it.

And perhaps --test-pattern argument should ignore all other arguments, because the following prints are obviously misaligned (canvas of a wrong size).

2023-11-08 21:22 UTC, maresb approved these changes

2023-11-08 21:23 UTC, maresb commented
Ok, just let me know when you're ready. It's good enough for me. I can't be bothered at the moment to fix #88.

2023-11-09 16:12 UTC, tomek-szczesny commented
I think this is ready for a pull.

2023-11-09 17:07 UTC, maresb commented
For discoverability, I'd like to do the matrix optimization removal in a separate PR. (I'm thinking that at some point in the future if we support huge labels then it'd be nice to have a clean reference to the point when that code was removed.)

That stuff can be super-annoying if you're not a frequent Git user. Would you like me to crank that out for you?

2023-11-09 17:14 UTC, tomek-szczesny commented
> For discoverability, I'd like to do the matrix optimization removal in a separate PR. (I'm thinking that at some point in the future if we support huge labels then it'd be nice to have a clean reference to the point when that code was removed.)
> 
> That stuff can be super-annoying if you're not a frequent Git user. Would you like me to crank that out for you?

I would appreciate that, thanks.

2023-11-09 17:19 UTC, maresb commented
> But I'm not sure if it makes any difference - it is a separate commit after all. 

This is true except for the automatic release notes, which are on a per-PR basis, and that's what I'm aiming for.

> You can pull in such a way that the whole pull request isn't seen as a single commit.

Ya, that's the squash-merge. I'll do it here.

2023-11-09 17:22 UTC, tomek-szczesny commented
Sorry, I just found one last bug. ;)

2023-11-09 17:26 UTC, maresb commented
@tomek-szczesny, I cherry-picked your commit to a branch `remove-dottab-matrix-opt`. Are you able to open a PR for it? For me it works via this link:
https://github.com/computerlyrik/dymoprint/compare/remove-dottab-matrix-opt?expand=1

2023-11-09 17:33 UTC, tomek-szczesny commented
@maresb sorry I can't. I have to be a collaborator, the error says.

2023-11-09 17:42 UTC, merged